"""every update

Revision ID: b285be2c6a46
Revises: 6afd183dd9dc
Create Date: 2024-03-08 18:55:47.257164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b285be2c6a46'
down_revision = '6afd183dd9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
